# Generated by Django 2.2 on 2020-03-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_administrator_name'),
        ('subject', '0011_auto_20200303_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('research_status', models.TextField(blank=True, null=True, verbose_name='研究现状综述')),
                ('feasibility_analysis', models.TextField(blank=True, null=True, verbose_name='可行性分析')),
                ('problems_and_solutions', models.TextField(blank=True, null=True, verbose_name='重点/关键问题及解决思路')),
                ('working_conditions', models.TextField(blank=True, null=True, verbose_name='课题工作条件')),
                ('programme_and_schedule', models.TextField(blank=True, null=True, verbose_name='工作方案及进度安排')),
                ('review_opinion', models.TextField(blank=True, null=True, verbose_name='审阅意见')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审阅时间')),
                ('review_result', models.IntegerField(choices=[(0, '待审阅'), (1, '合格'), (2, '不合格')], default=0, verbose_name='审核结果')),
                ('guide_teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Teacher', verbose_name='指导老师')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='课题')),
            ],
        ),
    ]
