# Generated by Django 3.1.7 on 2021-03-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名称')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='公司简介')),
                ('company_size', models.IntegerField(choices=[(1, '0-20'), (2, '20-99'), (3, '100-499'), (4, '500-999'), (5, '1000-9999'), (6, '>10000')], default=1, verbose_name='公司规模')),
                ('Legal_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='法人')),
                ('date_of_establishment', models.DateField(verbose_name='成立时间')),
                ('business_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='企业类型')),
                ('business_scope', models.TextField(blank=True, null=True, verbose_name='经营范围')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('other_info', models.JSONField(blank=True, default={}, null=True, verbose_name='其他信息')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label_type', models.IntegerField(choices=[(1, '技能'), (2, '福利')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='岗位名称')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='工作地点')),
                ('recruitment_status', models.IntegerField(choices=[(1, '招聘中'), (2, '停止招聘')], default=1, verbose_name='招聘状态')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='薪水')),
                ('work_experience', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='工作经验')),
                ('education', models.IntegerField(choices=[(1, '其他'), (2, '大专'), (3, '本科'), (4, '硕士'), (5, '博士')], default=1, verbose_name='教育')),
                ('recruiter', models.CharField(blank=True, max_length=255, null=True, verbose_name='照着')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='职位描述')),
                ('company', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company', verbose_name='公司')),
                ('skill_label', models.ManyToManyField(db_constraint=False, to='company.Label', verbose_name='skill_label')),
                ('welfare_label', models.ManyToManyField(db_constraint=False, related_name='welfare_label', to='company.Label', verbose_name='福利标签')),
            ],
        ),
    ]
