# Generated by Django 3.1.7 on 2021-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='other_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='其他信息'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='工作经验'),
        ),
    ]
