# Generated by Django 3.1.7 on 2021-03-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210313_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='job_direction',
            field=models.IntegerField(choices=[(1, 'JAVA开发'), (2, 'Python开发'), (3, 'PHP开发'), (4, '前端开发'), (5, '产品经理'), (6, '软件测试'), (7, '软件实施'), (8, 'UI设计'), (9, '互联网营销'), (10, '算法工程师'), (11, '区块链'), (12, '大数据'), (13, '云计算'), (14, '移动端开发'), (15, '游戏开发'), (16, '嵌入式开发'), (17, '运维工程师'), (18, 'golang开发')], null=True, verbose_name='岗位方向'),
        ),
    ]
