# Generated by Django 3.1.7 on 2021-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_jobposition_job_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(choices=[(1, '0-20'), (2, '20-99'), (3, '100-499'), (4, '500-999'), (5, '1000-9999'), (6, '>10000')], null=True, verbose_name='公司规模'),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_establishment',
            field=models.DateField(null=True, verbose_name='成立时间'),
        ),
    ]
