# Generated by Django 3.1.7 on 2021-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210314_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='recruiter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='招聘者'),
        ),
    ]
