# Generated by Django 2.2 on 2020-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_mvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='任务完成时间'),
        ),
    ]
