# Generated by Django 2.2 on 2020-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_mvc', '0002_auto_20200615_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='任务标题'),
        ),
    ]
