# Generated by Django 2.2 on 2020-06-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_mvc', '0003_auto_20200615_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_time',
        ),
    ]
