# Generated by Django 2.2 on 2019-12-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='账号名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('education', models.IntegerField(choices=[(0, '学士'), (1, '硕士'), (2, '博士')], default=1, verbose_name='学历')),
                ('teacher_title', models.IntegerField(choices=[(0, '助教'), (1, '讲师'), (2, '副教授'), (3, '教授')], default=1, verbose_name='职称')),
                ('phone', models.CharField(max_length=30, verbose_name='联系方式')),
                ('qq', models.CharField(max_length=30, verbose_name='QQ')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('is_monitor', models.BooleanField(default=False, verbose_name='是否是教研室负责人')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account', verbose_name='账户')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Faculty', verbose_name='学院')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Office', verbose_name='教研室')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('phone', models.CharField(max_length=30, verbose_name='联系方式')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('qq', models.CharField(max_length=30, verbose_name='QQ')),
                ('is_monitor', models.BooleanField(default=False, verbose_name='是否是班长')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account', verbose_name='账户')),
                ('diretcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Direction', verbose_name='方向')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Faculty', verbose_name='学院')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Klass', verbose_name='班级')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Profession', verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account', verbose_name='账户')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Faculty', verbose_name='学院')),
            ],
        ),
    ]
