# Generated by Django 2.2 on 2019-12-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default=None, max_length=30, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
