# Generated by Django 2.2 on 2020-03-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_administrator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('publish_content', models.TextField(verbose_name='')),
                ('publish_file', models.FileField(upload_to='announcement', verbose_name='')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Administrator', verbose_name='')),
            ],
        ),
    ]
