# Generated by Django 2.2 on 2020-03-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='publish_content',
            field=models.TextField(blank=True, null=True, verbose_name='发布内容'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_file',
            field=models.FileField(upload_to='announcement', verbose_name='发布文件'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Administrator', verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
    ]
