# Generated by Django 2.2 on 2020-02-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='review_result',
            field=models.IntegerField(blank=True, choices=[(0, '待审核'), (1, '审核通过'), (2, '审核未通过')], default=0, null=True, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='review_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Administrator', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='select_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='选题学生'),
        ),
    ]
