# Generated by Django 2.2 on 2020-02-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20200223_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='review_reason',
            field=models.TextField(blank=True, null=True, verbose_name='审批理由'),
        ),
    ]
