# Generated by Django 2.2 on 2020-02-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20200226_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='select_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='select_student', to='user.Student', verbose_name='选题学生'),
        ),
    ]
