# Generated by Django 2.2 on 2020-02-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_name'),
        ('subject', '0006_auto_20200227_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='apply_students',
        ),
        migrations.CreateModel(
            name='ApplySubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(blank=True, null=True, verbose_name='申请时间')),
                ('apply_result', models.IntegerField(default=0, verbose_name='申请结果')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='申请学生')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='申请的课题')),
            ],
        ),
    ]
