# Generated by Django 2.2 on 2020-03-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_name'),
        ('subject', '0007_auto_20200228_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_time', models.DateTimeField(verbose_name='任务书下达时间')),
                ('subject_desc', models.TextField(verbose_name='课题简述')),
                ('purpose_and_significance', models.TextField(verbose_name='研究的目的意义')),
                ('content_and_technology', models.TextField(verbose_name='主要的内容和技术')),
                ('data_and_information', models.TextField(verbose_name='原始的数据和资料')),
                ('schedule', models.TextField(verbose_name='进度安排')),
                ('references', models.TextField(verbose_name='参考资料')),
                ('information_in_English', models.TextField(verbose_name='英文资料翻译要求')),
                ('review_time', models.DateTimeField(verbose_name='审核时间')),
                ('review_result', models.IntegerField(choices=[(0, '待审核'), (1, '合格'), (2, '不合格')], default=0, verbose_name='审核结果')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Administrator', verbose_name='审核人')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='所属课题')),
            ],
        ),
    ]
