# Generated by Django 2.2 on 2020-03-03 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_taskbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbook',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_book', to='subject.Subject', verbose_name='所属课题'),
        ),
    ]
