# Generated by Django 2.2 on 2020-03-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_auto_20200303_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbook',
            name='content_and_technology',
            field=models.TextField(default='', verbose_name='主要的内容和技术'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='data_and_information',
            field=models.TextField(default='', verbose_name='原始的数据和资料'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='information_in_English',
            field=models.TextField(default='', verbose_name='英文资料翻译要求'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='purpose_and_significance',
            field=models.TextField(default='', verbose_name='研究的目的意义'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='references',
            field=models.TextField(default='', verbose_name='参考资料'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='schedule',
            field=models.TextField(default='', verbose_name='进度安排'),
        ),
        migrations.AlterField(
            model_name='taskbook',
            name='subject_desc',
            field=models.TextField(default='', verbose_name='课题简述'),
        ),
    ]
