# Generated by Django 2.2 on 2020-03-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0011_auto_20200303_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=250, verbose_name='关键词')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('thesis', models.FileField(blank=True, null=True, upload_to='thesis/', verbose_name='毕业论文文件')),
                ('upload_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('review_option', models.TextField(verbose_name='指导老师审核意见')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审阅时间')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='课题')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.FileField(blank=True, null=True, upload_to='design/', verbose_name='毕业设计文件')),
                ('upload_time', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('review_option', models.TextField(verbose_name='指导老师审核意见')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审阅时间')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject', verbose_name='课题')),
            ],
        ),
    ]
