# Generated by Django 2.2 on 2020-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationdesign',
            name='review_option',
            field=models.TextField(blank=True, null=True, verbose_name='指导老师审核意见'),
        ),
    ]
