# Generated by Django 2.2 on 2020-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20200310_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationthesis',
            name='review_option',
            field=models.TextField(blank=True, null=True, verbose_name='指导老师审核意见'),
        ),
        migrations.AlterField(
            model_name='graduationthesis',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
    ]
