# Generated by Django 2.2 on 2020-03-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20200310_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduationthesis',
            old_name='key_words',
            new_name='key_word',
        ),
    ]
