# Generated by Django 2.2 on 2020-03-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20200311_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduationthesis',
            old_name='key_word',
            new_name='words',
        ),
    ]
