# Generated by Django 2.2 on 2020-04-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_administrator_name'),
        ('organization', '0004_location'),
        ('design', '0005_auto_20200311_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_time', models.DateField(verbose_name='选择时间')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.Location', verbose_name='答辩地点')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='答辩学生')),
            ],
        ),
    ]
