# Generated by Django 2.2 on 2020-04-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_graduationreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationreply',
            name='select_time',
            field=models.DateTimeField(verbose_name='选择时间'),
        ),
    ]
