# Generated by Django 2.2 on 2020-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20200406_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationthesis',
            name='score',
            field=models.IntegerField(default=0, verbose_name='论文成绩'),
        ),
    ]
