# Generated by Django 2.2 on 2020-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_graduationthesis_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationthesis',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='论文成绩'),
        ),
    ]
