# Generated by Django 2.2 on 2020-03-18 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='主要内容')),
                ('annex', models.FileField(blank=True, null=True, upload_to='message/', verbose_name='附件')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发表时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_board_publisher', to=settings.AUTH_USER_MODEL, verbose_name='发表人')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messsage_board_receiver', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
        ),
    ]
