# Generated by Django 2.2 on 2019-12-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='方向名称')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='方向编号')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='学院名')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='学院编号')),
                ('monitor', models.CharField(max_length=30, verbose_name='院长')),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='班级名称')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='班级编号')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='教研室名称')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='教研室编号')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='专业名称')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='专业编号')),
            ],
        ),
    ]
