# Generated by Django 2.2.3 on 2022-03-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, unique=True, verbose_name='IP地址')),
                ('ip_addr', models.CharField(default='', max_length=100, verbose_name='IP地理位置')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '用户访问信息',
                'verbose_name_plural': '用户访问信息',
            },
        ),
        migrations.CreateModel(
            name='UserInterviewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('interview_url', models.CharField(default='', max_length=100, verbose_name='访问地址')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.UserIP', verbose_name='用户IP地址')),
            ],
        ),
    ]
